# Generated by Django 4.2.6 on 2023-12-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default='This is just a default', max_length=200),
            preserve_default=False,
        ),
    ]
