# Generated by Django 4.2.6 on 2023-12-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_commentitem_blog_remove_commentitem_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Department',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='blog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.department'),
        ),
    ]
