# Generated by Django 4.2.6 on 2023-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_checkout_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
